apiVersion: v2
name: tobs
description: A Helm chart for tobs, The Observability Stack for Kubernetes

type: application

version: 0.1.1
appVersion: 0.1.1

dependencies:
  - name: timescaledb-single
    condition: timescaledb-single.enabled
    version: 0.5.5
    repository: https://charts.timescale.com
  - name: promscale
    condition: promscale.enabled
    version: 0.1.1
    repository: https://charts.timescale.com
  - name: prometheus
    condition: prometheus.enabled
    version: 11.16.7
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    condition: grafana.enabled
    version: 6.1.0
    repository: https://grafana.github.io/helm-charts
