apiVersion: v2
name: tobs
description: A Helm chart for tobs, The Observability Stack for Kubernetes

type: application

version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: timescaledb-single
    condition: timescaledb-single.enabled
    version: 0.5.5
    repository: https://charts.timescale.com
  - name: promscale
    condition: promscale.enabled
    version: 0.1.0
    repository: https://charts.timescale.com
  - name: prometheus
    condition: prometheus.enabled
    version: 11.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: grafana
    condition: grafana.enabled
    version: 5.1.4
    repository: https://kubernetes-charts.storage.googleapis.com
