# Values for configuring the deployment of TimescaleDB
# The charts README is at: 
#    https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-single
# Check out the various configuration options (administration guide) at: 
#    https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md
timescaledb-single:
  # disable the chart if an existing TimescaleDB instance is used
  enabled: true
  # number or TimescaleDB pods to spawn (default is 3, 1 for no HA)
  replicaCount: 1

# Values for configuring the deployment of the Timescale Prometheus Connector
# The charts README is at:
#   https://github.com/timescale/prometheus-postgresql-adapter-private/tree/series-schema/helm-chart
timescale-prometheus:
  image: delixd/timescale-prometheus
  enabled: true
  password:
    create: false
    nameTemplate: "{{ .Release.Name }}-timescaledb-passwords"