{{ if .Values.timescaledbExternal.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-timescaledb-uri
  namespace: {{ template "tobs.namespace" . }}
  labels:
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  db-uri: {{ .Values.timescaledbExternal.db_uri | b64enc }}
  {{- end -}}