{{ if .Values.timescaledbExternal.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ template "tobs.namespace" . }}
  labels:
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ .Values.promscale.connection.password.timescaleDBSuperUserKey }}: {{ include "tobs.dburi.password" . | b64enc }}
{{- end -}}