{{ if .Values.grafana.enabled -}}
{{ if .Values.grafana.sidecar.datasources.enabled }}
{{- $tsEnabled := .Values.grafana.timescale.ds.enabled -}}
{{- $promEnabled := .Values.grafana.prometheus.ds.enabled -}}
{{- $anyDataSources := or $tsEnabled $promEnabled -}}
{{ if $anyDataSources -}}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    grafana_datasource: "1"
    app: {{ template "timescale-observability.fullname" . }}
    chart: {{ template "timescale-observability.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData: 
  datasource.yaml: |-
    # config file version
    apiVersion: 1
    
    datasources:
{{- if $promEnabled }}
      - name: Prometheus
        type: prometheus
        url: {{ tpl .Values.grafana.prometheus.ds.url . }}
        isDefault: true
        editable: true
        access: proxy
{{- end -}}
{{ if $tsEnabled -}}
{{- $isDefault := not $promEnabled -}}
{{- $root := . -}}
{{ with .Values.grafana.timescale.ds }}
      - name: TimescaleDB
        url: {{ tpl .host $root }}
        type: postgres
        isDefault: {{ $isDefault }}
        access: proxy
        user: {{ .user }}
        database: {{ .dbName }}
        editable: true
        secureJsonData:
          password: {{ .pass }}
        jsonData:
          sslmode: {{ .sslMode }}
          postgresVersion: 1000
          timescaledb: true
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
