{{ if .Values.grafana.enabled -}}
{{- $timescaleAsDB := .Values.grafana.timescale.database -}}
{{- $timescaleAsDS := .Values.grafana.timescale.datasource -}}
{{ if or $timescaleAsDB.enabled $timescaleAsDS.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-db
  labels:
   app: {{ template "timescale-observability.fullname" . }}
   chart: {{ template "timescale-observability.chart" . }}
   release: {{ .Release.Name }}
data:
  add-users.sql: |-
    \set ON_ERROR_STOP on
    {{ if $timescaleAsDB.enabled -}}
    DO $$
      BEGIN
        CREATE ROLE {{ $timescaleAsDB.user }} WITH LOGIN PASSWORD '{{ $timescaleAsDB.pass }}';
      EXCEPTION WHEN duplicate_object THEN 
        RAISE NOTICE 'role {{ $timescaleAsDB.user }} already exists, skipping create';
      END
    $$;
    CREATE SCHEMA IF NOT EXISTS {{ $timescaleAsDB.schema }} AUTHORIZATION {{ $timescaleAsDB.user }};
    ALTER ROLE {{ $timescaleAsDB.user }} SET search_path = {{ $timescaleAsDB.schema }};
    {{- end -}}
    {{- if $timescaleAsDS.enabled }}
    DO $$
      BEGIN
        CREATE ROLE prom_reader;
      EXCEPTION WHEN duplicate_object THEN
        RAISE NOTICE 'role prom_reader already exists, skipping create';
      END
    $$;
    DO $$
      BEGIN
        CREATE ROLE {{ $timescaleAsDS.user }} WITH LOGIN PASSWORD '{{ $timescaleAsDS.pass }}';
      EXCEPTION WHEN duplicate_object THEN
        RAISE NOTICE 'role {{ $timescaleAsDS.user }} already exists, skipping create';
      END
    $$;
    GRANT prom_reader TO {{ $timescaleAsDS.user }};
    {{- end -}}  
{{- end -}}
{{- end -}}