{{- if .Values.prometheus.enabled -}}
{{- if .Values.prometheus.server.enabled -}}
{{- if .Values.prometheus.server.configMapOverrideName -}}
{{- $promContext := dict "Release" .Release "Chart" .Chart "Values" .Values.prometheus -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.prometheus.server.configMapOverrideName }}
  labels:
    {{- include "prometheus.server.labels" $promContext | nindent 4 }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.prometheus.serverFiles }}
  {{ $key }}: |
{{- if eq $key "prometheus.yml" }}
    global:
{{ $root.Values.prometheus.server.global | toYaml | trimSuffix "\n" | indent 6 }}
{{- $tsPromValues := index $root.Values "timescale-prometheus" -}}
{{- $remoteWrite := $root.Values.prometheus.server.remoteWrite -}}
{{- $shouldHaveRemoteWriteKey := or $remoteWrite $tsPromValues.enabled -}}
{{- $dummyChart := dict "Name" "timescale-prometheus" -}}
{{- $tsPromContext := dict "Release" $root.Release "Chart" $dummyChart "Values" $tsPromValues -}}
{{- $tsPromUrl := printf "http://%s.%s.svc.cluster.local:%.0f" (include "timescale-observability.fullname" $tsPromContext) $root.Release.Namespace $tsPromValues.service.port -}}
{{- if $shouldHaveRemoteWriteKey }}
    remote_write:
{{- if $tsPromValues.enabled -}}
{{- $tsPromWriteUrl := printf " %s/write" $tsPromUrl }}
      - url: {{- $tsPromWriteUrl }}
        queue_config:
{{ toYaml $tsPromValues.remote.queue | indent 10 }}
{{- end }}
{{- if $remoteWrite }}
{{ $root.Values.prometheus.server.remoteWrite | toYaml | indent 6 }}
{{- end }}
{{- end }}
{{- $shouldHaveRemoteReadKey := or $root.Values.prometheus.server.remoteRead $tsPromValues.enabled -}}
{{- if $shouldHaveRemoteReadKey }}
    remote_read:
{{- if $tsPromValues.enabled }}
{{- $tsPromReadUrl := printf " %s/read" $tsPromUrl }}
      - url: {{- $tsPromReadUrl }}
{{- end }}
{{- if $root.Values.prometheus.server.remoteRead }}
{{ $root.Values.prometheus.server.remoteRead | toYaml | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq $key "alerts" }}
{{- if and (not (empty $value)) (empty $value.groups) }}
    groups:
{{- range $ruleKey, $ruleValue := $value }}
    - name: {{ $ruleKey -}}.rules
      rules:
{{ $ruleValue | toYaml | trimSuffix "\n" | indent 6 }}
{{- end }}
{{- else }}
{{ toYaml $value | indent 4 }}
{{- end }}
{{- else }}
{{ toYaml $value | default "{}" | indent 4 }}
{{- end }}
{{- if eq $key "prometheus.yml" -}}
{{- if $root.Values.prometheus.extraScrapeConfigs }}
{{ tpl $root.Values.prometheus.extraScrapeConfigs $root | indent 4 }}
{{- end -}}
{{- if or ($root.Values.prometheus.alertmanager.enabled) ($root.Values.prometheus.server.alertmanagers) }}
    alerting:
{{- if $root.Values.prometheus.alertRelabelConfigs }}
{{ $root.Values.prometheus.alertRelabelConfigs | toYaml  | trimSuffix "\n" | indent 6 }}
{{- end }}
      alertmanagers:
{{- if $root.Values.prometheus.server.alertmanagers }}
{{ toYaml $root.Values.prometheus.server.alertmanagers | indent 8 }}
{{- else }}
      - kubernetes_sd_configs:
          - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        {{- if $root.Values.prometheus.alertmanager.prefixURL }}
        path_prefix: {{ $root.Values.prometheus.alertmanager.prefixURL }}
        {{- end }}
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: {{ $root.Release.Namespace }}
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: {{ template "prometheus.name" $root }}
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_component]
          regex: alertmanager
          action: keep
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_probe]
          regex: {{ index $root.Values.prometheus.alertmanager.podAnnotations "prometheus.io/probe" | default ".*" }}
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex:
          action: drop
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}