{{ if .Values.grafana.enabled -}}
{{- $ds := .Values.grafana.sidecar.datasources -}}
{{ if $ds.enabled }}
{{- $tsEnabled := $ds.timescaledb.enabled -}}
{{- $promEnabled := $ds.prometheus.enabled -}}
{{- $anyDataSources := and $tsEnabled $promEnabled -}}
{{ if $anyDataSources -}}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    grafana_datasource: "1"
    app: {{ template "timescale-observability.fullname" . }}
    chart: {{ template "timescale-observability.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData: 
  datasource.yaml: |-
    # config file version
    apiVersion: 1
    
    datasources:
{{- if $promEnabled }}
      - name: Prometheus
        type: prometheus
        url: {{ tpl $ds.prometheus.urlTemplate . }}
        isDefault: true
        editable: true
        access: proxy
{{- end -}}
{{ if $tsEnabled -}}
{{- $isDefault := not $promEnabled }}
      - name: TimescaleDB
        url: {{ tpl $ds.timescaledb.urlTemplate . }}
        type: postgres
        isDefault: {{ $isDefault }}
        access: proxy
        user: {{ $ds.timescaledb.user }}
        database: postgres
        editable: true
        jsonData:
          sslmode: require
          postgresVersion: 1000
          timescaledb: true
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
