{{ if .Values.prometheus.server.enabled -}}
{{ if .Values.grafana.enabled -}}
{{- $promEnv := (set (set (deepCopy .) "Values" .Values.prometheus) "Chart" (dict "Name" "prometheus")) -}}
{{- $serverName := (include "prometheus.server.fullname" $promEnv) -}}
{{- $serverUrl := printf "http://%s.%s.svc.cluster.local:%.0f" $serverName .Release.Namespace .Values.prometheus.server.service.servicePort -}}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    grafana_datasource: "1"
    app: {{ template "timescale-observability.fullname" . }}
    chart: {{ template "timescale-observability.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData: 
  datasource.yaml: |-
    # config file version
    apiVersion: 1
    
    datasources:
      - name: Prometheus
        type: prometheus
        url: {{ $serverUrl }}
        isDefault: true
        editable: true
        access: proxy
{{- else -}}
# A prometheus data source for grafana is created only if grafana is enabled
{{- end -}}
{{- else -}}
# A prometheus data source for grafana is created only if the prometheus server is enabled
{{- end -}}
