name: Static deploy generation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v2

      - name: Test static generation
        run: |
          ./generate-deploy-script.sh
          # git diff --exit-code
